import type {Locale,L10n} from './types';
export const locales:Locale[]=['es','en','ay','qu'];
export const localeNames:Record<Locale,string>={es:'Español',en:'English',ay:'Aymara',qu:'Quechua'};
export const copy={
  nav:{home:{es:'Inicio',en:'Home',ay:'Qallta',qu:'Qallariy'},about:{es:'Quiénes somos',en:'About us',ay:'Khitinakasa',qu:'Pikunam kasqanchik'},services:{es:'Servicios',en:'Services',ay:'Servicios',qu:'Servicios'},news:{es:'Novedades',en:'News',ay:'Yatiyäwinaka',qu:'Musuq yachaykuna'},jobs:{es:'Convocatorias',en:'Openings',ay:'Irnaqäwinaka',qu:'Minkaykuna'},contact:{es:'Contacto',en:'Contact',ay:'Aruskipawi',qu:'Rimaykuy'},login:{es:'Mi espacio',en:'My space',ay:'Nayan espacio',qu:'Ñuqapa espacio'}},
  hero:{eyebrow:{es:'Talento que transforma Bolivia',en:'Talent transforming Bolivia',ay:'Bolivia markaru mayjt’ayaña talento',qu:'Boliviyata tikraq talento'},title:{es:'Tu próxima etapa empieza aquí.',en:'Your next chapter starts here.',ay:'Juman jutir saräwim akaw qallti.',qu:'Jamuq pacha kaypi qallarin.'},body:{es:'Conecta con el Banco de Desarrollo Productivo y encuentra oportunidades para aportar, crecer y construir futuro.',en:'Connect with Banco de Desarrollo Productivo and find opportunities to contribute, grow and build the future.',ay:'Banco de Desarrollo Productivo ukamp chikachasiña, irnaqäwinaka jikxataña.',qu:'Banco de Desarrollo Productivowan tinkuy, llamk’aypaqmi wiñaypaq wiñariy.'},cta:{es:'Explorar oportunidades',en:'Explore opportunities',ay:'Irnaqäwinaka uñjaña',qu:'Minkaykunata maskay'}} ,
  sections:{open:{es:'Convocatorias activas',en:'Open opportunities',ay:'Jichha irnaqäwinaka',qu:'Kunan minkaykuna'},openBody:{es:'Encuentra el lugar donde tu experiencia puede mover una economía.',en:'Find where your experience can move an economy.',ay:'Juman yatxäwim mä economía apnaqañapataki.',qu:'Yachayniki huk economíata kuyuchiyta atin.'},about:{es:'Un banco que cree en las personas',en:'A bank that believes in people',ay:'Jaquinakar iyawsiri banco',qu:'Runakunata iñiq banco'},aboutBody:{es:'Impulsamos el desarrollo productivo con inclusión, innovación y compromiso con Bolivia.',en:'We drive productive development through inclusion, innovation and commitment to Bolivia.',ay:'Bolivia markan nayrar sartawipa ch’amanchapxtan.',qu:'Boliviapa wiñariyninta kallpachayku.'},news:{es:'Novedades para tu camino',en:'News for your journey',ay:'Juman saräwimataki yatiyäwinaka',qu:'Ñanpaq musuq yachaykuna'},contact:{es:'Hablemos de tu próximo paso',en:'Let’s talk about your next step',ay:'Juman jutir thaqhawi aruskipañäni',qu:'Jamuq thaskiykimanta rimarisun'}} ,
  common:{apply:{es:'Postularme',en:'Apply now',ay:'Mayt’asiña',qu:'Minkakuy'},view:{es:'Ver detalle',en:'View details',ay:'Uñjaña',qu:'Qhawariy'},login:{es:'Ingresar',en:'Sign in',ay:'Mantantaña',qu:'Yaykuy'},register:{es:'Crear perfil',en:'Create profile',ay:'Perfil luraña',qu:'Perfil ruwana'},save:{es:'Guardar',en:'Save',ay:'Imaña',qu:'Waqaychay'},search:{es:'Buscar',en:'Search',ay:'Thaqhaña',qu:'Maskay'},close:{es:'Cerrar',en:'Close',ay:'Jist’antaña',qu:'Wichqay'}}
} as const;
export type Copy=typeof copy;
export const t=(value:L10n,locale:Locale)=>value[locale]||value.es;
export const c=(value:Record<Locale,string>,locale:Locale)=>value[locale]||value.es;
export function href(path:string,locale:Locale){return `/${locale}${path==='/'?'':path}`}
